sudo: false
language: ruby
cache: bundler
rvm:
- 2.3.3
install:
- bundle install
script: bundle exec rake site:deploy
env:
  global:
    secure: AIzkNS84gCLGE4zf34DY2+uCFULaXSGCAGykqze8AkoRw2VCmuXKqj/313JmX1BlI/jE5TzCza05j+HjYFSgqnT8EMCIfdIFa+KbFG0YRUeLn4HM9MI7nfCCp0NXo1Mn4mbPf5rKXp7j/Iu7DwlhwOq5K3QSK+VThdf/e3+74+hf4/TuQh/lLw4QmeNJcvTEgD6+Kx3tolsvaWfGQ+wwd87bbjwKRw4WzC8/qPBRh0txVtBfKqZEEXM3shnlQMJXQaLurXlbLQIpDokUfyjUwhZWxObimaNcEOBeIgqWff5uW5OGS/nvax2QFn7zqvA61PvXjLeoyrAX+E3AJ4qITiQpLnGoyoxQQ3ZwDfEAgkUOozRp27RLPZRZOYY9tlZpv3nJudrkCIWSmSIVQkACaGWiOaaKfLiENAX+esVxqM0vTzMhfhT/wNGXtUfTvFHDYSn5jqJypvBVSevllDs4rf//Qi5VbvnL1Eouqyog8aTv+P+kVM06XwJDToo7qyAA7OTL12CNu1lwXubj8rPdnSDXs+QfMnEN4ky5ErX7ccGlBwMyHYUcFT/qYsw0SCLGayei+dfkYdIK9iC4Dp5hzUzfAV5/aW+yftRzVKgv5RvqoXOICDigJHMtZbHvYgqUjViBqkQF8F1bPIudovfrCRA4ckD1CSJAm2xne9Xb5w0=
branches:
  only:
  - source
